[package]
name = "host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "submit_bin"
path = "src/submit_bin.rs"

[[bin]]
name = "extract_imageid"
path = "src/extract_imageId.rs"

[dependencies]
methods = { workspace = true }
risc0-zkvm = { workspace = true, default-features = true }
serde_json     = "1.0"
alloy = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.0", features = ["derive", "env"] }
env_logger = { version = "0.10" }
log = { workspace = true }
risc0-ethereum-contracts = { workspace = true }
tokio = { version = "1.35", features = ["full"] }
url = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
bincode = { workspace = true }
hex = { workspace = true }
ethereum-types = { workspace = true }
sha2 = "0.10"
