// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant IS_EVEN_ID = bytes32(0x575630cd75dd7d27fedd4aaeea7d050076e1e6ffd5d506c524b11517931a3143);
    bytes32 public constant MERKEL_ID = bytes32(0x2be1764b19cea59dac5cf05a831b4d7ce8446dba69fc39d1621235b97ac20030);
}
