[package]
name = "nesting_guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "2.3.1", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
risc0-zkp = { version = "2.0.1", default-features = false }
ethereum-types = "0.14"