[package]
name = "nullifier_verifier_core"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"


[dependencies]
signature_verifier_core = {path = "../signature_verifier_core/"}
ethereum-types = { version = "0.14", default-features = false }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
