use ethers::abi::AbiEncode;
use std::fs;
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use loaders::loaders::{
    load_all_merkle_proofs, load_nullifiers, load_signatures, load_user_owned_addresses,
};
use methods::{DEFI_INPUTS_VALIDATOR_ELF, DEFI_INPUTS_VALIDATOR_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts};
use shared::{DefiProofInput, DefiProofOutput};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // 1. Loading the defi data that is supposed to be verified:
    // TODO: We need to aggree on message that we will use to create signing.
    // NOTE: in this case the signatres and nullifiers where generated with message = "Block 2"
    let message = "Block 2";
    let all_signatures = load_signatures("defi_inputs/signatures.json").unwrap();
    let all_nullifiers = load_nullifiers("defi_inputs/nullifiers.json").unwrap();
    let all_merkle_proofs = load_all_merkle_proofs("defi_inputs/all_merkle_proofs.json").unwrap();
    let user_owned_addresses =
        load_user_owned_addresses("defi_inputs/user_owned_addresses.json").unwrap();
    let proofInputs: DefiProofInput = DefiProofInput {
        all_signatures,
        all_nullifiers,
        owned_accounts_addresses: user_owned_addresses,
        owned_accounts_merkle_proofs: all_merkle_proofs.owned_accounts_merkle_proofs,
        storage_merkle_proofs: all_merkle_proofs.user_history_proof.storage_merkle_proofs,
        contract_merkle_proof: all_merkle_proofs.user_history_proof.contract_merkle_proof,
        contract_address: all_merkle_proofs.user_history_proof.contract_address,
        user_address: all_merkle_proofs.user_history_proof.user_address,
        message: message.to_string(),
        trusted_state_root: all_merkle_proofs.user_history_proof.state_root,
    };

    // passing inputs to the guest
    let env = ExecutorEnv::builder()
        .write(&proofInputs)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    // let prove_info = prover.prove(env, DEFI_INPUTS_VALIDATOR_ELF).unwrap();
    println!("Running the prover...");
    let opts = ProverOpts::succinct();
    let prove_info = prover
        .prove_with_opts(env, DEFI_INPUTS_VALIDATOR_ELF, &opts)
        .unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(DEFI_INPUTS_VALIDATOR_ID).unwrap();
    println!("Receipt verification successful!");

    // decoding journal
    let _output: DefiProofOutput = receipt.journal.decode().unwrap();
    println!("Output: {:?}", _output);

    // Save the receipt to receipt.bin
    println!("\nSaving receipt to receipt.bin...");
    let receipt_bytes = bincode::serialize(&receipt).unwrap();
    let bytes_len = receipt_bytes.len();
    fs::write("invalid_defi_inputs_receipt.bin", receipt_bytes).unwrap();
    println!(
        "Receipt saved to invalid_defi_inputs_receipt.bin ({} bytes)",
        bytes_len
    );
}
