[package]
name = "defi_inputs_validator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "2.3.1",  features = ['std','unstable'] }
merkle_verifier_core = { path = "../../../../lib/core/merkle_verifier_core/",default-features = false }
signature_verifier_core = { path = "../../../../lib/core/signature_verifier_core/",default-features = false }
nullifier_verifier_core = { path = "../../../../lib/core/nullifier_verifier_core/",default-features = false }
shared = {path = "../../shared/"}
ethereum-types = "0.14"

[patch.crates-io]
# Use RISC Zero's accelerated versions for precompiles
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
