[package]
name = "guest"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
risc0-zkvm = { version = "2.1.0", default-features = false, features = ["std"] }
serde = { workspace = true }
risc0-zkp = { workspace = true }
ethereum-types = { workspace = true }

[profile.release]
lto = "thin"
