[package]
name = "guest"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
score_calculation = { path = "../../lib/core/score_calculation" }
risc0-zkvm = { version = "2.3.1", default-features = false, features = ["std"] }
serde = { workspace = true }
risc0-zkp = { workspace = true }
ethereum-types = { workspace = true }
alloy-sol-types = "0.8"

[profile.release]
lto = "thin"
